Lance/boo joint v2
poolpitako/joint-strategy pull request #12
Opened 2021-05-03 21:17 UTC by LanceUp

changes in naming

2021-05-03 21:21 UTC, poolpitako requested changes

2021-05-03 21:21 UTC, poolpitako commented on contracts/BooJoint.sol
> +contract BooJointWftmBoo {
Plz keep the `BooJoint` name.

2021-05-03 21:21 UTC, poolpitako commented on contracts/BooJoint.sol
> +        return masterchef.pendingCake(pid, address(this));
it needs to be `.pendingBOO`

2021-05-03 21:27 UTC, LanceUp commented on contracts/BooJoint.sol
> +        return masterchef.pendingCake(pid, address(this));
done in V3, thanks!

2021-05-03 21:27 UTC, LanceUp commented on contracts/BooJoint.sol
> +contract BooJointWftmBoo {
done in V3, thanks!

2021-05-03 22:01 UTC, poolpitako commented on contracts/BooJoint.sol
> +        return masterchef.pendingBoo(pid, address(this));
pretty sure this is case sensitive. use `.pendingBOO`

2021-05-04 01:04 UTC, poolpitako approved these changes

2021-05-04 01:05 UTC, merged